### PR TITLE
Silence unused param on Mac

### LINKED ISSUE #908: Unused parameter warning treated as error during build for MacOS
Hi,

I'm trying to build slangpy on my machine using `pip install .` after cloning. During the compilation I get the following error due to the -Werror flag (Clang 20.1.2 on MacOS):

```
_slangpy/src/sgl/device/cuda_utils.cpp:174:69: error: unused parameter 'luid' [-Werror,-Wunused-parameter]
        174 | inline int find_device_by_luid(int device_count, const AdapterLUID& luid)
            |                                                                     ^
      1 error generated._
```

If I manually go to the file (cuda_utils.cpp) and comment the variable name out

```
inline int find_device_by_luid(int device_count, const AdapterLUID& /*luid*/)
```

It compiles fine with me. If you want I can create a PR for this...

### PR DESCRIPTION
**Pull request by jkwak-work**
Fixes https://github.com/shader-slang/slangpy/issues/908

## Summary by CodeRabbit

* **Chores**
  * Cleans up a compiler warning in CUDA-related utilities to reduce noisy build output; purely a build-time/maintenance change with no impact on functionality or end-user behavior.

### CODE REVIEW

**Review by jhelferty-nv — DISMISSED** [review]

File: src/sgl/device/cuda_utils.cpp [hunk 1]
```diff
@@ -173,6 +157,7 @@ void wait_external_semaphore(CUexternalSemaphore ext_sem, uint64_t value, CUstre
 
 inline int find_device_by_luid(int device_count, const AdapterLUID& luid)
 {
+    (void)luid;
```
Comment (ccummingsNV) [inline src/sgl/device/cuda_utils.cpp]: we have SGL_UNUSED for this

**Review by ccummingsNV — DISMISSED** [review]
