### PR TITLE
Fix asmjit usage on old x86_64

### LINKED ISSUE #364: vfmadd213sd use incorrectly gated by AVX feature flag
`src/sgl/core/data_struct.cpp` incorrectly uses the AVX feature flag to gate the use of `vfmadd213sd`, instead of the FMA feature flag, which results in an illegal instruction error on my (old) i7-3820.

### PR DESCRIPTION
**Pull request by jhelferty-nv**
Fixes #364

Fixed detection and fallback paths for old x86_64 processors when deciding what instructions to generate using asmjit

### CODE REVIEW

File: src/sgl/core/data_struct.cpp [hunk 1]
```diff
@@ -736,6 +736,8 @@ struct X86Program : public Program {
         asmjit::x86::Compiler& c;
         bool has_avx;
         bool has_f16c;
+        bool has_sse4_1;
```
Comment (skallweitNV) [inline src/sgl/core/data_struct.cpp]: do we really need to support the case where SSE 4.1 is not supported? seems like that would only be the case on really really old CPUs that have no business running slangpy?!

**Review by skallweitNV — COMMENTED** [review]
The AVX checks make sense, I'd get rid of the sse4.1 check though

File: src/sgl/core/data_struct.cpp (hunk 1 above)
Comment (skallweitNV) [reply src/sgl/core/data_struct.cpp]: To elaborate a bit, my worry is that there might be more places where we rely on SSE 4.1?! Without properly testing this on a platform that doesn't have SSE 4.1, we're probably better of falling back to the non-jitted version if basic SSE is not available.

Comment (jhelferty-nv) [reply src/sgl/core/data_struct.cpp]: I'm not sure, tbh. I only added it because it was easy to get an LLM to generate it, and the test suite passed when I forced all of the 'has' features to false.

Comment (jhelferty-nv) [reply src/sgl/core/data_struct.cpp]: Either way, the branch is only evaluated at generation time. I don't think it should impact performance of the fast path.

Comment (jhelferty-nv) [reply src/sgl/core/data_struct.cpp]: Per discussion, instead of providing an asmjit path for processors without SSE 4.1, the code now falls back to non-asmjit path.
