### PR TITLE
Fix array-type returns

### LINKED ISSUE #380: Very poor errors when attempting to coerce Tensors with array types
From Tizian

Here is a short reproducer:
shape = (4096 * 4096 * 8,)
tensor = spy.Tensor.empty(module.device, shape, 'half')
tensor.storage.copy_from_numpy(np.zeros(shape, dtype=np.float16))
tensor = tensor.with_grads(zero=True)

module['tensor_test_channels<8>'](tensor)
for
half[NumChannels] tensor_test_channels<int NumChannels>(half[NumChannels] data)
{
    [ForceUnroll]
    for (int i = 0; i < NumChannels; ++i)
    {
        data[i] = 2.h * data[i];
    }
    return data;
}
[1:55](https://nvidia.slack.com/archives/C07JB8BB7Q8/p1753707347775299?thread_ts=1753701420.569139&cid=C07JB8BB7Q8)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\src\Falcor-nm-slangpy\external\slangpy\slangpy\core\function.py", line 348, in __call__
    return self.call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\src\Falcor-nm-slangpy\external\slangpy\slangpy\core\function.py", line 231, in call
    return self._native_call(self.module.call_data_cache, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\src\Falcor-nm-slangpy\external\slangpy\slangpy\builtin\valueref.py", line 221, in create_output
    pt = slang_type_to_return_type(self.value_type)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\src\Falcor-nm-slangpy\external\slangpy\slangpy\builtin\value.py", line 66, in slang_type_to_return_type
    raise ValueError(f"Slang type {slang_type} has no associated python value type")
ValueError: Slang type Object(0x1aa307d24f8) has no associated python value type
[1:58](https://nvidia.slack.com/archives/C07JB8BB7Q8/p1753707533301159?thread_ts=1753701420.569139&cid=C07JB8BB7Q8)
The other issue seems to be that I cannot pass a shape (N, N, 8) of half into that function. Only (N, N) of half[8].
new_buffer_channels_wrong = spy.NDBuffer(module.device, 'half',    shape=(128, 128, 8))
new_buffer_channels_right = spy.NDBuffer(module.device, 'half[8]', shape=(128, 128))
I can bypass this with some slightly more awkward
test = spy.NDBuffer.empty(module.device, shape=(4096, 4096), dtype='half[8]')
test.copy_from_numpy(array)
instead of
spy.NDBuffer.from_numpy(module.device, array)
(array.shape == (4096, 4096, 8))

### PR DESCRIPTION
**Pull request by NV-xiaoyongs**
Fixes #380 

Fix array-type returns (e.g. half[8]) and improve NDBuffer.from_numpy for array dtypes:
- Fix poor error when returning Slang array types like half[8]; map ArrayType to Python lists.
- Update ValueRef marshalling to allocate/read/write ArrayType outputs correctly.
- Improve NDBuffer.from_numpy(..., dtype="half[8]") to infer buffer shape by stripping trailing element-shape dims (e.g. (H,W,8) -> (H,W)).
- Add tests covering half[8] return values and array-dtype buffer construction.

### CODE REVIEW

File: src/sgl/core/lmdb_cache.cpp [hunk 1]
```diff
@@ -129,23 +129,40 @@ void LMDBCache::set(const void* key_data, size_t key_size, const void* value_dat
...
-        LMDB_THROW("Failed to write data", result);
-
-    MetaData meta_data{.last_access = get_current_time_ns()};
-    MDB_val mdb_val_meta = {sizeof(MetaData), &meta_data};
-    if (int result = mdb_put(txn, m_db.dbi_meta, &mdb_key, &mdb_val_meta, 0); result != MDB_SUCCESS)
-        LMDB_THROW("Failed to write metadata", result);
-
-    txn.commit();
+    // LMDB map size limits are based on committed pages, not just active payload size.
+    // Eviction should be triggered based on committed size to avoid MDB_MAP_FULL before
```
Comment (ccummingsNV) [inline src/sgl/core/lmdb_cache.cpp]: This should be in a separate PR, and reviewed by @skallweitNV

File: slangpy/builtin/valueref.py [hunk 2]
```diff
@@ -223,6 +226,8 @@ def read_calldata(
     def create_output(self, context: CallContext, binding: BoundVariableRuntime) -> Any:
         pt = slang_type_to_return_type(self.value_type)
         if pt is not None:
+            # For arrays this will create an empty list; the actual value will be filled during
```
Comment (ccummingsNV) [inline slangpy/builtin/valueref.py]: Suggest this is redundant comment (unless you want to specify what happens for other types)

File: slangpy/builtin/valueref.py [hunk 3]
```diff
@@ -170,15 +170,18 @@ def create_calldata(
...
                     element_count=1,
                     struct_size=binding.vector_type.buffer_layout.stride,
                     usage=BufferUsage.shader_resource | BufferUsage.unordered_access,
                 )
                 cursor = BufferCursor(binding.vector_type.buffer_layout.reflection, buffer, False)
-                cursor[0].write(data.value)
-                cursor.apply()
+                # For write-only outputs, the initial Python value may be just a placeholder
+                # (e.g. [] for half[8]). Don't pre-initialize GPU memory in that case.
+                if access[0] == AccessType.readwrite:
```
Comment (ccummingsNV) [inline slangpy/builtin/valueref.py]: Suggest access[0] != AccessType.write 
That way you have 2 advantages:
- if enum changes in future this line is less likely to become wrong,
- the functionality of this 'if' is not dependent on that on line 170
Both less likely to create future bugs

File: slangpy/builtin/value.py [hunk 4]
```diff
@@ -60,6 +60,9 @@ def slang_type_to_return_type(slang_type: kfr.SlangType) -> Any:
             return getattr(slangpy, f"uint{slang_type.rows}x{slang_type.cols}")
         elif slang_type.slang_scalar_type in BOOL_TYPES:
             return getattr(slangpy, f"bool{slang_type.rows}x{slang_type.cols}")
+    elif isinstance(slang_type, kfr.ArrayType):
+        # Arrays are represented as nested Python lists when returned as a value.
```
Comment (ccummingsNV) [inline slangpy/builtin/value.py]: Suggest this is redundant comment

File: slangpy/tests/slangpy_tests/test_array_return_arrays.py [hunk 5]
```diff
@@ -0,0 +1,76 @@
...
+"""
+
+
+@pytest.mark.parametrize("device_type", helpers.DEFAULT_DEVICE_TYPES)
+def test_return_array_value_from_python_list(device_type: DeviceType):
+    device = helpers.get_device(device_type)
+    module = helpers.create_module(device, MODULE)
+
+    # Scalar call (no vectorization): return type is half[8] as a Python value.
+    func = module.find_function("tensor_test_channels<8>")
```
Comment (ccummingsNV) [inline slangpy/tests/slangpy_tests/test_array_return_arrays.py:33]: Does this work if you rely on slangpy to do the generic resolution (i.e. just find 'tensor_test_channels' and pass it an array of length 8). No problem if not, but if it does, would be good to add a test to verify that stays working.

**Review by ccummingsNV — CHANGES_REQUESTED** [review]
Few suggested changes with code maintenance / other engineers in mind, but looks good. 

The lmdb work should be in a separate PR though as far as I can tell.

File: src/sgl/core/lmdb_cache.cpp (hunk 1 above)
Comment (skallweitNV) [reply src/sgl/core/lmdb_cache.cpp]: Agreed this should be a separate PR. I'll have to review this in more detail, but overall looks like the right direction.

Comment (NV-xiaoyongs) [reply src/sgl/core/lmdb_cache.cpp]: removed

File: slangpy/builtin/valueref.py (hunk 2 above)
Comment (NV-xiaoyongs) [reply slangpy/builtin/valueref.py]: removed

File: slangpy/builtin/valueref.py (hunk 3 above)
Comment (NV-xiaoyongs) [reply slangpy/builtin/valueref.py]: updated

File: slangpy/builtin/value.py (hunk 4 above)
Comment (NV-xiaoyongs) [reply slangpy/builtin/value.py]: removed

File: slangpy/tests/slangpy_tests/test_array_return_arrays.py (hunk 5 above)
Comment (NV-xiaoyongs) [reply slangpy/tests/slangpy_tests/test_array_return_arrays.py:33]: Confirmed: generic resolution works. Calling tensor_test_channels (no <8>) with a Python list of length 8 resolves NumChannels = 8. I added a regression test (test_return_array_value_generic_resolution) to ensure this stays working.

File: src/sgl/core/lmdb_cache.cpp (hunk 1 above)
Comment (skallweitNV) [reply src/sgl/core/lmdb_cache.cpp]: @NV-xiaoyongs will you open a new PR for the lmdb cache bug? Would be greatly appreciated.

File: slangpy/tests/slangpy_tests/test_array_return_arrays.py (hunk 5 above)
Comment (ccummingsNV) [reply slangpy/tests/slangpy_tests/test_array_return_arrays.py:33]: Thanks!

File: src/sgl/core/lmdb_cache.cpp (hunk 1 above)
Comment (skallweitNV) [reply src/sgl/core/lmdb_cache.cpp]: no need anymore .. opened #739
